# Generated by Django 3.0.5 on 2020-06-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
    ]
