# Generated by Django 3.0.5 on 2020-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customer_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Order',
        ),
    ]
