# Generated by Django 3.0.5 on 2020-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200627_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='00000', max_length=30),
            preserve_default=False,
        ),
    ]
