# Generated by Django 3.0.5 on 2020-07-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
    ]
