# Generated by Django 3.0.5 on 2020-07-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_has_responded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='has_responded',
            new_name='responded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
