# Generated by Django 3.0.5 on 2020-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200704_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
