# Generated by Django 3.0.5 on 2020-07-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=2500),
        ),
    ]
