# Generated by Django 3.0.5 on 2020-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
