# Generated by Django 3.0.5 on 2020-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_phone', models.CharField(max_length=15)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.EmailField(max_length=100)),
                ('postal', models.TextField()),
                ('photo_url', models.FileField(blank=True, null=True, upload_to='contact')),
                ('publish', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
