# Generated by Django 3.0.5 on 2020-08-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200728_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='has_responded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
