# Generated by Django 3.0.5 on 2020-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactmessage_has_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(default='response'),
            preserve_default=False,
        ),
    ]
