# Generated by Django 3.0.5 on 2020-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactmessage_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
    ]
