# Generated by Django 3.0.5 on 2020-07-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0004_auto_20200727_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publish', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('blog_img', models.FileField(upload_to='blog')),
                ('img_title', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
                ('blog_category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory')),
                ('post_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='Post By')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
