# Generated by Django 3.0.5 on 2020-06-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HepepsTeam',
        ),
    ]
