# Generated by Django 3.0.5 on 2020-07-06 14:20

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_auto_20200620_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('training_description', models.CharField(blank=True, max_length=200, null=True)),
                ('training_cert', models.CharField(blank=True, max_length=200, null=True)),
                ('training_company', models.CharField(blank=True, max_length=200, null=True)),
                ('training_location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField()),
                ('team_member_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='team_member_ID')),
            ],
            options={
                'verbose_name_plural': 'Training',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('status', models.BooleanField()),
                ('team_member_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='team_member_ID')),
            ],
            options={
                'verbose_name_plural': 'Publication',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField()),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField()),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff_profile.Countries', verbose_name='Country')),
                ('team_member_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='team_member_ID')),
            ],
            options={
                'verbose_name_plural': 'Work Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField()),
                ('end_date', partial_date.fields.PartialDateField()),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField()),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff_profile.Countries', verbose_name='Country')),
                ('team_member_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='team_member_ID')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('cert_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('team_member_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='team_member_ID')),
            ],
            options={
                'verbose_name_plural': 'Certification',
            },
        ),
    ]
