# Generated by Django 3.0.5 on 2020-07-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='training',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff_profile.Countries', verbose_name='Country'),
        ),
    ]
