# Generated by Django 3.0.5 on 2020-07-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200620_0852'),
        ('staff_profile', '0002_auto_20200710_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('status', models.BooleanField()),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('tools_use', models.TextField()),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff_profile.Countries', verbose_name='Country')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Role', verbose_name='Role')),
                ('team_member_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.Team', verbose_name='team_member_ID')),
            ],
            options={
                'verbose_name_plural': 'Projects Managed',
            },
        ),
    ]
