# Generated by Django 3.0.5 on 2020-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
