# Generated by Django 3.0.5 on 2020-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0004_auto_20200712_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
