# Generated by Django 3.0.5 on 2020-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0006_auto_20200712_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='method_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
