# Generated by Django 3.0.5 on 2020-07-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0007_projects_method_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='team_member_ID',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='team_member_ID',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='team_member_ID',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='team_member_ID',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='team_member_ID',
            new_name='team',
        ),
    ]
