# Generated by Django 3.0.5 on 2020-07-27 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0009_auto_20200727_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Bio',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='team',
            name='img_url',
            field=models.FileField(upload_to='staff'),
        ),
    ]
