# Generated by Django 3.0.5 on 2020-07-27 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0010_auto_20200727_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='status',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='team_member_ID',
        ),
        migrations.RemoveField(
            model_name='education',
            name='status',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='training',
            name='status',
        ),
        migrations.AddField(
            model_name='certifications',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certifications',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='training',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='training',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Countries'),
        ),
        migrations.AlterField(
            model_name='education',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Team'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Countries'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Team', verbose_name='team_member_ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Countries'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_desc',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Role'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Team'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tools_use',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Team'),
        ),
        migrations.AlterField(
            model_name='training',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Countries'),
        ),
        migrations.AlterField(
            model_name='training',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Team'),
        ),
    ]
