# Generated by Django 3.0.5 on 2020-07-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0011_auto_20200727_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(default='my school', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Country'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Country'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Country'),
        ),
        migrations.AlterField(
            model_name='training',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_profile.Country'),
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
