# Generated by Django 3.0.5 on 2020-07-27 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0012_auto_20200727_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='cert_name',
            field=models.CharField(default='cert', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certifications',
            name='description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
