# Generated by Django 3.0.5 on 2020-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0013_auto_20200727_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='institution',
            field=models.CharField(default='cert inst.', max_length=250),
            preserve_default=False,
        ),
    ]
