# Generated by Django 3.0.5 on 2020-07-27 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0015_auto_20200727_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='training_cert',
            field=models.CharField(default='cert', max_length=200),
            preserve_default=False,
        ),
    ]
