# Generated by Django 3.0.5 on 2020-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0016_auto_20200727_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
