# Generated by Django 3.0.5 on 2020-07-27 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0017_auto_20200727_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_desc',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='role',
        ),
        migrations.AddField(
            model_name='projects',
            name='client_name',
            field=models.CharField(default='client', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default='desc', max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='role_on_project',
            field=models.CharField(default='role', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='company_name',
            field=models.CharField(default='company', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='method_use',
            field=models.CharField(default='method', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='tools_use',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
