# Generated by Django 3.0.5 on 2020-07-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0018_auto_20200727_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='method_use',
            new_name='method_used',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='tools_use',
            new_name='tools_used',
        ),
    ]
