# Generated by Django 3.0.5 on 2020-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0020_auto_20200727_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='reference',
            new_name='description',
        ),
        migrations.AddField(
            model_name='publication',
            name='reference_link',
            field=models.TextField(default='des', max_length=256),
            preserve_default=False,
        ),
    ]
